name=input("Enter your name:\n")
print("Hello",name,", Welcome to the calc2!")
a=int(input("Enter the first number:\n"))
b=int(input("Enter the second number:\n"))
print("the value of", a, "+", b, "is: ",a+b) 
print("The value of", a, "-", b, "is: ",a-b)
print("The value of", a, "*", b, "is: ",a*b)
print("The value of", a, "/", b, "is: ",a/b)
print("The value of", a, "%", b, "is: ",a%b)
